ClassBookApplication/Controllers/API/ClassesController.cs
using ClassBookApplication.DataContext;
using ClassBookApplication.Domain.Classes;
using ClassBookApplication.Factory;
using ClassBookApplication.Models.RequestModels;
using ClassBookApplication.Models.ResponseModel;
using ClassBookApplication.Service;
using ClassBookApplication.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ClassBookApplication.Controllers.API
{
    [ApiVersion("1")]
    public class ClassesController : MainApiController
    {
        #region Fields

        private readonly ClassBookManagementContext _context;
        private readonly ClassBookService _classBookService;
        private readonly ClassBookModelFactory _classBookModelFactory;

        #endregion

        #region Ctor

        public ClassesController(ClassBookManagementContext context,
            ClassBookService classBookService,
            ClassBookModelFactory classBookModelFactory)
        {
            this._context = context;
            this._classBookService = classBookService;
            this._classBookModelFactory = classBookModelFactory;
        }

        #endregion

        #region Register Classes

        // POST api/Classes/Register
        [HttpPost("Register")]
        public async Task<IActionResult> Register([FromForm] CommonRegistrationModel model)
        {
            ResponseModel responseModel = new ResponseModel();
            if (ModelState.IsValid)
            {
                Classes classesData = JsonConvert.DeserializeObject<Classes>(model.Data.ToString());
                if (classesData != null)
                {
                    var singleUser = _context.Users.Where(x => x.Email == classesData.Email).AsNoTracking();
                    if (!singleUser.Any())
                    {
                        (int classesId, string uniqueNo) = _classBookService.SaveClasses(classesData, model.Files, model.Video);
                        string UserName = (classesData.Name + uniqueNo).Replace(" ", string.Empty);
                        //_classBookService.SaveMappingData((int)Module.Classes, classesId, classesData.MappingRequestModel);
                        var user = _classBookService.SaveUserData(classesId, Module.Classes, UserName, classesData.Email, model.FCMId, model.DeviceId);
                        var rest = _classBookService.RegisterMethod(model, "/api/v1/ChannelPartner/register");
                        await Task.Run(() => _classBookService.SendVerificationLinkEmail(classesData.Email, user.Password, Module.Classes.ToString()));
                        responseModel.Message = ClassBookConstantString.Register_Classes_Success.ToString();
                        responseModel.Data = _classBookModelFactory.PrepareUserDetail(user);
                        return StatusCode((int)HttpStatusCode.OK, responseModel);
                    }
                    else
                    {
                        responseModel.Message = ClassBookConstantString.Validation_EmailExist.ToString();
                        return StatusCode((int)HttpStatusCode.Conflict, responseModel);
                    }
                }
                return StatusCode((int)HttpStatusCode.BadRequest);
            }
            else
            {
                return StatusCode((int)HttpStatusCode.BadRequest, ModelState);
            }

        }

        // POST api/Classes/EditClasses
        [HttpPost("EditClasses")]
        public IActionResult EditClasses([FromForm] CommonRegistrationModel model)
        {
            ResponseModel responseModel = new ResponseModel();
            if (ModelState.IsValid)
            {
                Classes classesData = JsonConvert.DeserializeObject<Classes>(model.Data.ToString());
                if (classesData != null)
                {
                    if (_context.Users.Count(x => x.Email == classesData.Email && x.EntityId != classesData.Id) > 0)
                    {
                        responseModel.Message = ClassBookConstantString.Validation_EmailExist.ToString();
                        return StatusCode((int)HttpStatusCode.Conflict, responseModel);
                    }
                    else
                    {
                        var singleClass = _context.Classes.Where(x => x.Id == classesData.Id).AsNoTracking().FirstOrDefault();
                        int classId = _classBookService.UpdateClasses(classesData, singleClass, model.Files);
                        //_classBookService.SaveMappingData((int)Module.Classes, classId, classesData.MappingRequestModel);
                        responseModel.Message = ClassBookConstantString.Edit_Classes_Success.ToString();
                        return StatusCode((int)HttpStatusCode.OK, responseModel);
                    }
                }
                return StatusCode((int)HttpStatusCode.BadRequest);
            }
            else
            {
                return StatusCode((int)HttpStatusCode.BadRequest, ModelState);
            }
        }

        #endregion

        #region GetClassesDetails

        // GET api/Classes/GetAllClasses
        [HttpGet("GetAllClasses")]
        public IEnumerable<ListingModel> GetAllClasses()
        {
            return _classBookService.GetModuleDataByModuleId((int)Module.Classes);
        }

        // GET api/Classes/GetClassById/5
        [HttpGet("GetClassById/{id:int}")]
        public object GetClassById(int id)
        {
            var query = from classes in _context.Classes
                        join city in _context.City on classes.CityId equals city.Id
                        where classes.Id == id && classes.Active == true
                        orderby classes.Id
                        select new CommonDetailModel
                        {
                            Id = classes.Id,
                            Name = classes.Name,
                            CityName = city.Name,
                            IntroductionURL = _classBookModelFactory.PrepareURL(classes.IntroductionURL)
                        };
            var ClassData = query.FirstOrDefault();
            if (ClassData != null)
                ClassData.BoardMediumStandardModel = _classBookService.GetDetailById(ClassData.Id, (int)Module.Classes);
            return ClassData;
        }

        // GET api/Classes/EditProfileForClass/5
        [HttpGet("EditProfileForClass/{id:int}")]
        public object EditProfileForClass(int id)
        {
            var query = from classes in _context.Classes
                        join state in _context.States on classes.StateId equals state.Id
                        join city in _context.City on classes.CityId equals city.Id
                        join pincode in _context.Pincode on classes.Pincode equals pincode.Id
                        where classes.Id == id && classes.Active == true
                        orderby classes.Id
                        select new
                        {
                            Name = classes.Name,
                            Email = classes.Email,
                            ContactNo = classes.ContactNo,
                            AlternateContact = classes.AlternateContact,
                            RegistrationNo = classes.RegistrationNo,
                            LogoUrl = classes.LogoUrl,
                            ClassPhotoUrl = classes.ClassPhotoUrl,
                            EstablishmentDate = classes.EstablishmentDate,
                            Address = classes.Address,
                            TeachingExperience = classes.TeachingExperience,
                            Description = classes.Description,
                            ReferCode = classes.ReferCode,
                            UniqueNo = classes.UniqueNo,
                            StateName = state.Name,
                            CityName = city.Name,
                            Pincode = pincode.Name
                        };
            var ClassData = query.FirstOrDefault();
            return ClassData;
        }

        // GET api/Classes/GetClassInformationByReferCode
        [HttpGet("GetClassInformationByReferCode")]
        public object GetClassInformationByReferCode(string referCode)
        {
            var query = from classes in _context.Classes
                        where classes.ReferCode == referCode && classes.Active == true
                        select new
                        {
                            Name = classes.Name,
                            UniqueId = classes.UniqueNo
                        };
            return query.ToList();
        }


        //// GET api/Classes/GetClassStatistics/5
        //[HttpGet("GetClassStatistics/{id:int}")]
        //public object GetClassStatistics(int id)
        //{


        //}

        #endregion
    }
}

ClassBookApplication/Controllers/ClassController.cs
using ClassBookApplication.DataContext;
using ClassBookApplication.Domain.Classes;
using ClassBookApplication.Factory;
using ClassBookApplication.Models.PublicModel;
using ClassBookApplication.Service;
using ClassBookApplication.Utility;
using JW;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClassBookApplication.Controllers
{
    public class ClassController : Controller
    {
        #region Fields

        private readonly ClassBookModelFactory _classBookModelFactory;
        private readonly LogsService _logsService;
        private readonly ClassBookManagementContext _context;
        private readonly ClassBookService _classBookService;
        private readonly IViewRenderService _viewRenderService;

        #endregion

        #region Ctor

        public ClassController(ClassBookModelFactory classBookModelFactory,
            LogsService logsService,
            ClassBookManagementContext context,
            ClassBookService classBookService,
            IViewRenderService viewRenderService)
        {
            _classBookModelFactory = classBookModelFactory;
            _logsService = logsService;
            _context = context;
            _classBookService = classBookService;
            _viewRenderService = viewRenderService;
        }

        #endregion

        #region Method

        public IActionResult Register()
        {
            ClassRegisterModel model = new ClassRegisterModel();
            model = LoadModel(ref model);
            return View(model);
        }

        [HttpPost]
        public IActionResult Register(ClassRegisterModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var singleUser = _context.Users.Where(x => x.Email == model.Email).AsNoTracking();
                    if (!singleUser.Any())
                    {
                        List<IFormFile> list = new List<IFormFile>();
                        if (model.ImageFile != null)
                            list.Add(model.ImageFile);

                        Classes classData = new Classes()
                        {
                            Name = model.Name,
                            Email = model.Email,
                            AlternateContact = model.AlternateContact,
                            ContactNo = model.ContactNo,
                            EstablishmentDate = model.EstablishmentDate,
                            Address = model.Address,
                            StateId = model.StateId,
                            CityId = model.CityId,
                            Pincode = model.PincodeId,
                            RegistrationNo = model.RegistrationNo,
                            TeachingExperience = model.TeachingExperience
                        };
                        (int studentId, string uniqueNo) = _classBookService.SaveClasses(classData, list);
                        string UserName = classData.Name + uniqueNo;
                        var user = _classBookService.SaveUserData(studentId, Module.Student, UserName, classData.Email);
                        //var rest = _classBookService.RegisterMethod(model, "/api/v1/ChannelPartner/register");
                        _classBookService.SendVerificationLinkEmail(classData.Email, user.Password, Module.Student.ToString());
                        return RedirectToAction("Register");
                    }
                    else
                    {
                        ModelState.AddModelError("Email", "Email Id Already Exist");
                        model = LoadModel(ref model);
                    }
                    return View(model);
                }
                else
                {
                    model = LoadModel(ref model);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                _logsService.InsertLogs("Classes", ex, "Classes", 0);
                return RedirectToAction("Register");
            }
        }

        [HttpGet]
        public IActionResult AllClassesList()
        {
            int count = 0;
            ClassListModel model = new ClassListModel();
            model.States = _classBookModelFactory.PrepareStateDropDown();
            model.BoardList = _classBookModelFactory.PrepareBoardDropDown();
            model.MediumList = _classBookModelFactory.PrepareMediumDropDown();
            model.StandardList = _classBookModelFactory.PrepareStandardDropDown();
            FilterParameter filterParameterModel = new FilterParameter();
            model.ClassModel = _classBookService.AllClassesListModel(filterParameterModel, out count, 1);
            model.Pager = new Pager(count, 1);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AllClassesList(FilterParameter model)
        {
            int count;
            ClassListModel classmodel1 = new ClassListModel();
            classmodel1.ClassModel = _classBookService.AllClassesListModel(model, out count, model.PageIndex);
            classmodel1.Pager = new Pager(count, model.PageIndex);
            var result = await _viewRenderService.RenderToStringAsync("_ClassListPartialView", classmodel1);
            return Content(result);
        }

        [HttpGet]
        public IActionResult GetClass(int id)
        {
            var query = from classes in _context.Classes
                        where classes.Id == id && classes.Active == true
                        orderby classes.Id
                        select new ClassDetailModel
                        {
                            Id = classes.Id,
                            ClassName = classes.Name,
                            Address = classes.Address,
                            Email = classes.Email,
                            ContactNo = classes.ContactNo,
                            Website = "http://abcd.com/",
                            IntroductionVideoUrl = _classBookModelFactory.PrepareURL(classes.IntroductionURL),
                            ProfilePhoto = _classBookModelFactory.PrepareURL(classes.ClassPhotoUrl),
                            Description = classes.Description,
                            TotalRating = 4,
                        };
            ClassDetailModel classData = query.FirstOrDefault();
            var query1 = from smb in _context.StandardMediumBoardMapping
                         join board in _context.Board on smb.BoardId equals board.Id
                         join medium in _context.Medium on smb.MediumId equals medium.Id
                         join std in _context.Standards on smb.StandardId equals std.Id
                         where smb.EntityId == id && smb.ModuleId == (int)Module.Classes
                         select new StandardMediumBoardMappingData
                         {
                             SmbId= smb.Id,
                             BoardId = board.Id,
                             BoardName = board.Name,
                             MediumId = medium.Id,
                             MediumName = medium.Name,
                             StandardId = std.Id,
                             StandardName = std.Name,
                         };
            var standardMapping = query1.ToList();
            classData.StandardMediumBoardMapping = standardMapping;
            Dictionary<int, int> rating = new Dictionary<int, int>();
            rating.Add(1, 1000);
            rating.Add(2, 2000);
            rating.Add(3, 3000);
            rating.Add(4, 4000);
            rating.Add(5, 5000);
            classData.Ratings = rating.OrderByDescending(obj => obj.Key).ToDictionary(obj => obj.Key, obj => obj.Value);
            return View(classData);
        }

        #endregion

        #region Utilities

        protected ClassRegisterModel LoadModel(ref ClassRegisterModel model)
        {
            model.States = _classBookModelFactory.PrepareStateDropDown();
            return model;
        }

        #endregion
    }
}

ClassBookApplication/Views/Class/Register.cshtml
@model ClassRegisterModel
@{
    ViewData["Title"] = "Class Register";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<section>
    <div class="bannerimg">
        <div class="header-text mb-0 mt-5">
            <div class="container">
                <div class="text-center text-black">
                    <h1>Class Registration</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="sptb">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-md-12">
                <div class="card ">
                    <div class="card-body">
                        <form asp-action="Register" asp-controller="Class" enctype="multipart/form-data" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="form-label text-dark"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Email" class="form-label text-dark"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ContactNo" class="form-label text-dark"></label>
                                <input asp-for="ContactNo" class="form-control" />
                                <span asp-validation-for="ContactNo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AlternateContact" class="form-label text-dark"></label>
                                <input asp-for="AlternateContact" class="form-control" />
                                <span asp-validation-for="AlternateContact" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Address" class="form-label text-dark"></label>
                                <input asp-for="Address" class="form-control" />
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EstablishmentDate" class="form-label text-dark"></label>
                                <input asp-for="EstablishmentDate" class="form-control" />
                                <span asp-validation-for="EstablishmentDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StateId" class="form-label text-dark"></label>
                                <select asp-for="StateId"
                                        asp-items="@(new SelectList(Model.States,"Value","Text"))" class="form-control">
                                    <option value="0">Please Select</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="CityId" class="form-label text-dark"></label>
                                <select asp-for="CityId"
                                        asp-items="@(new SelectList(Model.Cities,"Value","Text"))" class="form-control">
                                    <option value="0">Please Select</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="PincodeId" class="control-label"></label>
                                <select asp-for="PincodeId"
                                        asp-items="@(new SelectList(Model.Pincodes,"Value","Text"))" class="form-control">
                                    <option value="0">Please Select</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="TeachingExperience" class="form-label text-dark"></label>
                                <input asp-for="TeachingExperience" class="form-control" placeholder="1.2 Years" />
                                <span asp-validation-for="TeachingExperience" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="RegistrationNo" class="form-label text-dark"></label>
                                <input asp-for="RegistrationNo" class="form-control" />
                                <span asp-validation-for="RegistrationNo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageFile" class="control-label"></label>
                                <div class="col-md-10">
                                    <input type="file" name="ImageFile" />
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Submit" class="btn btn-default btn-danger" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                @await Component.InvokeAsync("RegistrationSide")
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        $("#StateId").change(function () {
            var id = $(this).val();
            $("#CityId").empty();
            $.get("/Common/GetCities", { stateId: id }, function (data) {
                var v = "<option value='0'>---Select City---</option>";
                console.log(data);
                $.each(data, function (i, v1) {
                    v += "<option value=" + v1.value + ">" + v1.text + "</option>";
                });
                $("#CityId").html(v);
            });
        });
        $("#CityId").change(function () {
            var id = $(this).val();
            $("#PincodeId").empty();
            $.get("/Common/GetPincodes", { cityId: id }, function (data) {
                var v = "<option value='0'>---Select Pincodes---</option>";
                console.log(data);
                $.each(data, function (i, v1) {
                    v += "<option value=" + v1.value + ">" + v1.text + "</option>";
                });
                $("#PincodeId").html(v);
            });
        });
    });
</script>